const types = {
  LOG_IN_REQUESTED: 'LOG_IN_REQUESTED',
  LOG_IN_SUCCEEDED: 'LOG_IN_SUCCEEDED',
  LOG_IN_FAILED: 'LOG_IN_FAILED',
  SIGN_UP_REQUESTED: 'SIGN_UP_REQUESTED',
  SIGN_UP_SUCCEEDED: 'SIGN_UP_SUCCEEDED',
  SIGN_UP_FAILED: 'SIGN_UP_FAILED',
  LOG_OUT_REQUESTED: 'LOG_OUT_REQUESTED',
  LOG_OUT: 'LOG_OUT',
  CHANGE_DARK_THEME: 'CHANGE_DARK_THEME',
  CHANGE_TOUCH_ID: 'CHANGE_TOUCH_ID',
};

export default types;
